BEGIN;

CREATE TABLE IF NOT EXISTS snippets (
id SERIAL PRIMARY KEY ,
title VARCHAR(100) NOT NULL,
content TEXT NOT NULL,
created TIMESTAMPTZ NOT NULL,
expires TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_snippets_created ON snippets(created);

CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    hashed_password CHAR(60) NOT NULL,
    created TIMESTAMPTZ NOT NULL
);

ALTER TABLE users ADD CONSTRAINT users_uc_email UNIQUE(email);

COMMIT;