// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"
)

type Snippet struct {
	ID      int32
	Title   string
	Content string
	Created time.Time
	Expires time.Time
}

type User struct {
	ID             int32
	Name           string
	Email          string
	HashedPassword string
	Created        time.Time
}
