// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	GetLatestSnippets(ctx context.Context) ([]*Snippet, error)
	GetSnippet(ctx context.Context, id int32) (*Snippet, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id int32) (*User, error)
	InsertSnippet(ctx context.Context, arg InsertSnippetParams) (int32, error)
	InsertUser(ctx context.Context, arg InsertUserParams) error
}

var _ Querier = (*Queries)(nil)
